### ISSUE TITLE
PPF-015: Create mock API

### ISSUE THREAD

**Issue by 1amG4bor** [The-PET-project/PET-project-frontend#17]
- Mock API with CRUD operations for **User**, **Pet**, and  **PetOwner**/**PetCarer** entities

**Tasks:**
- [ ] Create mock services to handle CRUD operations with mock objects (based on the API documentation)
- [ ] Configure an HTTP-client (_Axios or something else_) to handle HTTP requests
- [ ] Create API interfaces based on the API documentation (user-API, pet-API, pet-owner-API, pet-carer-API)
- Write unit tests to validate the mock-API and HTTP-client configuration

Entity descriptions and API documentation can be found: [API-document-plan](https://docs.google.com/spreadsheets/d/1J59BH4tWJ9CDWjlfHpoufALpzkjpY8mjOuV3FQB5oHY/edit#gid=1685110266)
